################################################################################
# Welcome screen

#
# Messages that are shown when the same channel is already installed.
#

# {0} - application full name
# {1} - channel name
WelcomeAppInstalledSameChannelLabel1 = {0} {1} is already installed. Launch {0} by double-clicking the icon on your desktop:

# {0} - channel name
WelcomeAppInstalledSameChannelLabel2 = Click Next to re-install {0}. Click Cancel to launch from your desktop.

#
# Messages that are shown when a different channel is already installed.
#

# {0} - application full name
WelcomeAppInstalledDifferentChannelLabel1 = {0} is already installed. Launch {0} by double-clicking the icon on your desktop:
WelcomeAppInstalledDifferentChannelLabel2 = Then click "Show all fields" in the bottom left corner to expand the Login box and use the selector to choose a different version.

# {0} - channel name
WelcomeAppInstalledDifferentChannelLabel3 = Click Next to install {0} manually. Click Cancel to use the Version selector.

################################################################################
# Finish screen

# {0} - application full name
# this is a standard key that is overriden here
FinishedLabel = Setup has finished installing {0} on your computer. Launch {0} by double-clicking the icon on your desktop:

################################################################################
# Misc

# NTWS-14818: {0} - shared library name, {1} - FAQ URL, {2} - Support Center URL, {3} - application full name
MissingSharedLibraryText = <p>This application requires the {0} library, which is not installed on your system.</p><p>Please install it using your package manager, then run this installer again.</p><p>If you experience any issues during installation or setup, please contact our support team through the <a href="{2}">Support Center</a>.</p><p>For runtime issues after installation, please first check our FAQ: <a href="{1}">Why can I not run or update {3}?</a></p>

# NTWS-14818: {0} - shared library name, {1} - FAQ URL, {2} - application full name
MissingSharedLibraryText_WB = <p>This application requires the {0} library, which is not installed on your system.</p><p>Please install it using your package manager, then run this installer again.</p><p>For runtime issues after installation, please first check our FAQ: <a href="{1}">Why can I not run or update {2}?</a></p>
	