
import sys
sys.path.insert(0, '/opt/sigma')
from engine.optimization.asset_pipeline import (
    STRATEGIES, STRATEGIES_SHORT, STRATEGIES_ADAPTIVE, STRATEGIES_EXPLORE
)
print("LONG:", len(STRATEGIES), STRATEGIES)
print("SHORT:", len(STRATEGIES_SHORT), STRATEGIES_SHORT)
print("ADAPTIVE:", len(STRATEGIES_ADAPTIVE), STRATEGIES_ADAPTIVE)
print("EXPLORE:", len(STRATEGIES_EXPLORE), STRATEGIES_EXPLORE)
total = len(STRATEGIES)+len(STRATEGIES_SHORT)+len(STRATEGIES_ADAPTIVE)+len(STRATEGIES_EXPLORE)
print("TOTAL:", total)
