[IBC]
# SIGMA ENGINE - IBC Configuration
# ReadOnly=yes: NO ejecuta trades, solo descarga datos historicos

IbLoginId=donpadre1313
IbPassword=Undertaker123_
FIXLoginId=
FIXPassword=
TradingMode=live
ReadOnlyLogin=yes
AcceptNonBrokerageAccountWarning=yes
ExistingSessionDetectedAction=secondary
ReloginAfterSecondFactorAuthenticationTimeout=yes
AcceptBidAskLastSizeDisplayUpdateNotification=yes
AllowBlindTrading=no
CloseModalDialogsAutomatically=yes
DismissPasswordExpiryWarning=yes
DismissNSEComplianceNotice=yes
EnableBidAskLast=no
ForceTwsApiPort=4001
GetNextOrderId=yes
IbAutoClosedown=yes
IbControllerHeartbeatRate=10
IbOrderRolloverTime=1700
IbTimeZone=
LogComponents=never
MinimizeMainWindow=yes
OverrideTwsApiPort=4001
SendTWSLogsToIBC=no
StoreSettingsOnServer=no
